# config/_default/languages.en.toml

title = "Marco Payr"

[params.author]
name = "Marco Payr"
image = "img/me.jpg"
headline = "PhD student EMBL Heidelberg. Boehringer Ingelheim Fonds Alumnus <br> <br> Biochemist (Ph.D., EMBL) with an interdisciplinary background in chemistry. Hands-on expertise in expression, purification and design of recombinant, bioconjugated biomolecules (proteins, nanobodies, RNA). Proficient in design and development of analytical assays for protein characterization and passionate about working in interdisciplinary projects. <br><br> Mail: firstname.lastname@C.de, where C = EMBL"
links = [{linkedin = "https://www.linkedin.com/in/marco-payr-631854b7/"}]
